import type {
  Company, User, DocumentItem, LegalAnalysis, TaxAnalysis,
  DecisionRecommendation, AuditLog, GraphNode, GraphEdge,
} from "./types";

export const companies: Company[] = [
  { id: "co-1", name: "Kapazi Industrial Ltda", sector: "Indústria" },
  { id: "co-2", name: "Varejo Nacional S.A.", sector: "Varejo" },
  { id: "co-3", name: "Indústria Sul Brasil", sector: "Indústria" },
  { id: "co-4", name: "Consultoria Tributária Alpha", sector: "Consultoria" },
  { id: "co-5", name: "Escritório Fadel Demo", sector: "Jurídico" },
];

export const users: User[] = [
  { id: "u-1", email: "ceo@cognia.demo", name: "Delmer Zoschke", role: "CEO", companyId: "co-1" },
  { id: "u-2", email: "juridico@cognia.demo", name: "Renata Almeida", role: "Diretor Jurídico", companyId: "co-1" },
  { id: "u-3", email: "tributario@cognia.demo", name: "Nathan Endrigo", role: "Diretor Tributário", companyId: "co-1" },
  { id: "u-4", email: "admin@cognia.demo", name: "Fabio Canestraro", role: "Administrador", companyId: "co-1" },
  { id: "u-5", email: "cfo@cognia.demo", name: "Mariana Costa", role: "CFO", companyId: "co-1" },
];

export const adminUsers = [
  { name: "Delmer Zoschke", role: "CEO" },
  { name: "Fabio Canestraro", role: "CTO" },
  { name: "Davi Fadel", role: "Inteligência Jurídica" },
  { name: "Nathan Endrigo", role: "Inteligência Tributária" },
  { name: "Alexandre Brambilla", role: "Comercial" },
  { name: "Mariana Costa", role: "CFO cliente" },
  { name: "Renata Almeida", role: "Diretora Jurídica cliente" },
  { name: "Bruno Martins", role: "Analista Fiscal cliente" },
];

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86400000).toISOString();

export const initialLegalAnalyses: LegalAnalysis[] = [
  {
    id: "leg-1",
    processNumber: "0001234-56.2026.5.09.0001",
    companyId: "co-1",
    processType: "Trabalhista",
    claimant: "João da Silva",
    defendant: "Kapazi Industrial Ltda",
    lawyers: "Dr. Almeida & Associados",
    court: "1ª Vara do Trabalho de Curitiba",
    uf: "PR",
    estimatedValue: 113000,
    riskScore: 72,
    risk: "alto",
    confidence: 84,
    validationStatus: "pendente",
    responsible: "Renata Almeida",
    createdAt: daysAgo(1),
    summary:
      "Processo trabalhista com pedidos relacionados a horas extras, intervalo intrajornada, adicional de insalubridade e verbas rescisórias. A análise preliminar indica risco médio-alto em razão da documentação incompleta de jornada e histórico de decisões desfavoráveis em casos semelhantes.",
    parties: [
      { role: "Reclamante", name: "João da Silva" },
      { role: "Reclamada", name: "Kapazi Industrial Ltda" },
      { role: "Advogado Reclamante", name: "Dr. Almeida & Associados" },
      { role: "Vara/Tribunal", name: "1ª Vara do Trabalho de Curitiba — TRT9" },
    ],
    claims: [
      { claim: "Horas extras", estimatedValue: 48000, category: "Jornada", risk: "alto", confidence: 86 },
      { claim: "Intervalo intrajornada", estimatedValue: 22000, category: "Jornada", risk: "medio", confidence: 82 },
      { claim: "Adicional de insalubridade", estimatedValue: 35000, category: "Adicionais", risk: "alto", confidence: 78 },
      { claim: "Multa do art. 477", estimatedValue: 8000, category: "Rescisórias", risk: "baixo", confidence: 91 },
    ],
    recommendations: [
      "Revisar documentos de controle de jornada",
      "Avaliar proposta de acordo até R$ 42.000",
      "Solicitar documentos complementares ao RH",
      "Priorizar validação por especialista jurídico",
      "Classificar contingência como possível/provável conforme revisão humana",
    ],
    sources: [
      "Documento processual enviado",
      "Histórico interno mockado da empresa",
      "Casos similares mockados",
      "Base trabalhista simulada",
      "Validação pendente do especialista",
    ],
    riskJustification: [
      "Ausência de controles completos de jornada",
      "Valor potencial relevante (>R$ 100k)",
      "Pedidos recorrentes na unidade",
      "Histórico de risco em casos similares",
      "Baixa documentação de defesa",
    ],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-a3f8b2c1",
    estimatedCost: 0.42,
  },
  {
    id: "leg-2",
    processNumber: "0002231-14.2026.5.02.0031",
    companyId: "co-2",
    processType: "Trabalhista",
    claimant: "Maria Souza",
    defendant: "Varejo Nacional S.A.",
    lawyers: "Castro Advogados",
    court: "31ª Vara do Trabalho de São Paulo",
    uf: "SP",
    estimatedValue: 64000,
    riskScore: 48,
    risk: "medio",
    confidence: 79,
    validationStatus: "pendente",
    responsible: "Renata Almeida",
    createdAt: daysAgo(2),
    summary:
      "Pedido de equiparação salarial e acúmulo de função. Documentação parcial indica risco médio. Recomenda-se análise da estrutura de cargos.",
    parties: [
      { role: "Reclamante", name: "Maria Souza" },
      { role: "Reclamada", name: "Varejo Nacional S.A." },
      { role: "Vara/Tribunal", name: "31ª VT São Paulo — TRT2" },
    ],
    claims: [
      { claim: "Equiparação salarial", estimatedValue: 38000, category: "Salário", risk: "medio", confidence: 76 },
      { claim: "Acúmulo de função", estimatedValue: 18000, category: "Função", risk: "medio", confidence: 74 },
      { claim: "Dano moral", estimatedValue: 8000, category: "Moral", risk: "baixo", confidence: 70 },
    ],
    recommendations: ["Validar organograma", "Avaliar acordo até R$ 25.000", "Solicitar descrição de cargos ao RH"],
    sources: ["Petição inicial mockada", "Histórico interno", "Base trabalhista simulada"],
    riskJustification: ["Estrutura de cargos sobreposta", "Sem política formal de função"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-b1e9d4c2",
    estimatedCost: 0.38,
  },
  {
    id: "leg-3",
    processNumber: "0008452-88.2025.5.12.0044",
    companyId: "co-3",
    processType: "Trabalhista",
    claimant: "Carlos Mendes",
    defendant: "Indústria Sul Brasil",
    lawyers: "Mendes & Lima",
    court: "44ª VT Florianópolis",
    uf: "SC",
    estimatedValue: 198000,
    riskScore: 88,
    risk: "critico",
    confidence: 91,
    validationStatus: "pendente",
    responsible: "Davi Fadel",
    createdAt: daysAgo(3),
    summary: "Múltiplos pedidos cumulativos com forte risco de procedência. Histórico de jurisprudência regional desfavorável.",
    parties: [
      { role: "Reclamante", name: "Carlos Mendes" },
      { role: "Reclamada", name: "Indústria Sul Brasil" },
      { role: "Vara/Tribunal", name: "44ª VT Florianópolis — TRT12" },
    ],
    claims: [
      { claim: "Horas extras", estimatedValue: 72000, category: "Jornada", risk: "critico", confidence: 92 },
      { claim: "Adicional noturno", estimatedValue: 28000, category: "Adicionais", risk: "alto", confidence: 88 },
      { claim: "Verbas rescisórias", estimatedValue: 64000, category: "Rescisórias", risk: "alto", confidence: 90 },
      { claim: "Dano moral", estimatedValue: 34000, category: "Moral", risk: "medio", confidence: 73 },
    ],
    recommendations: ["Priorizar acordo", "Reforçar defesa técnica", "Revisar contingência para provável"],
    sources: ["Processo mockado", "Histórico regional", "Casos similares"],
    riskJustification: ["Valor crítico", "Jurisprudência desfavorável", "Pedidos cumulativos consistentes"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-c8a1e5f3",
    estimatedCost: 0.51,
  },
  {
    id: "leg-4",
    processNumber: "0007781-22.2026.5.03.0101",
    companyId: "co-1",
    processType: "Trabalhista",
    claimant: "Paula Ribeiro",
    defendant: "Kapazi Industrial Ltda",
    lawyers: "Ribeiro Advocacia",
    court: "101ª VT Belo Horizonte",
    uf: "MG",
    estimatedValue: 42000,
    riskScore: 28,
    risk: "baixo",
    confidence: 82,
    validationStatus: "aprovado",
    responsible: "Renata Almeida",
    createdAt: daysAgo(7),
    summary: "Pedidos rescisórios padrão com documentação completa de jornada. Baixa probabilidade de procedência integral.",
    parties: [
      { role: "Reclamante", name: "Paula Ribeiro" },
      { role: "Reclamada", name: "Kapazi Industrial Ltda" },
      { role: "Vara/Tribunal", name: "101ª VT BH — TRT3" },
    ],
    claims: [
      { claim: "Verbas rescisórias", estimatedValue: 28000, category: "Rescisórias", risk: "baixo", confidence: 88 },
      { claim: "Multa art. 477", estimatedValue: 14000, category: "Rescisórias", risk: "baixo", confidence: 84 },
    ],
    recommendations: ["Manter defesa atual", "Acompanhar audiência"],
    sources: ["Documento processual", "RH interno"],
    riskJustification: ["Documentação completa", "Histórico favorável"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-d2c4a7b9",
    estimatedCost: 0.31,
  },
  {
    id: "leg-5",
    processNumber: "0003344-77.2026.5.04.0012",
    companyId: "co-3",
    processType: "Trabalhista",
    claimant: "Roberto Lima",
    defendant: "Indústria Sul Brasil",
    lawyers: "Lima Sociedade",
    court: "12ª VT Porto Alegre",
    uf: "RS",
    estimatedValue: 88000,
    riskScore: 64,
    risk: "alto",
    confidence: 77,
    validationStatus: "corrigido",
    responsible: "Davi Fadel",
    createdAt: daysAgo(9),
    summary: "Pedidos de insalubridade e periculosidade simultâneas. Análise corrigida pelo especialista.",
    parties: [
      { role: "Reclamante", name: "Roberto Lima" },
      { role: "Reclamada", name: "Indústria Sul Brasil" },
      { role: "Vara/Tribunal", name: "12ª VT Porto Alegre — TRT4" },
    ],
    claims: [
      { claim: "Adicional de insalubridade", estimatedValue: 44000, category: "Adicionais", risk: "alto", confidence: 79 },
      { claim: "Adicional de periculosidade", estimatedValue: 32000, category: "Adicionais", risk: "medio", confidence: 71 },
      { claim: "Reflexos", estimatedValue: 12000, category: "Reflexos", risk: "medio", confidence: 75 },
    ],
    recommendations: ["Solicitar perícia técnica", "Avaliar acordo"],
    sources: ["Processo mockado", "Laudo interno"],
    riskJustification: ["Pedidos cumulativos vedados em parte", "Necessidade de perícia"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-e5b3f1a2",
    estimatedCost: 0.44,
  },
  {
    id: "leg-6",
    processNumber: "0005512-09.2026.5.15.0078",
    companyId: "co-2",
    processType: "Trabalhista",
    claimant: "Sandra Costa",
    defendant: "Varejo Nacional S.A.",
    lawyers: "Costa & Pires",
    court: "78ª VT Campinas",
    uf: "SP",
    estimatedValue: 56000,
    riskScore: 52,
    risk: "medio",
    confidence: 68,
    validationStatus: "pendente",
    responsible: "Renata Almeida",
    createdAt: daysAgo(4),
    summary: "Análise preliminar com confiança média. Requer atenção do especialista jurídico.",
    parties: [
      { role: "Reclamante", name: "Sandra Costa" },
      { role: "Reclamada", name: "Varejo Nacional S.A." },
      { role: "Vara/Tribunal", name: "78ª VT Campinas — TRT15" },
    ],
    claims: [
      { claim: "Horas extras", estimatedValue: 32000, category: "Jornada", risk: "medio", confidence: 70 },
      { claim: "Intervalo intrajornada", estimatedValue: 14000, category: "Jornada", risk: "medio", confidence: 66 },
      { claim: "Dano moral", estimatedValue: 10000, category: "Moral", risk: "baixo", confidence: 60 },
    ],
    recommendations: ["Validar com especialista", "Solicitar mais documentos"],
    sources: ["Processo mockado", "Base trabalhista simulada"],
    riskJustification: ["Baixa confiança em parte dos pedidos"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-f7d2c4e1",
    estimatedCost: 0.36,
  },
  {
    id: "leg-7",
    processNumber: "0009923-41.2025.5.09.0089",
    companyId: "co-1",
    processType: "Trabalhista",
    claimant: "Eduardo Pinto",
    defendant: "Kapazi Industrial Ltda",
    lawyers: "Pinto Associados",
    court: "89ª VT Curitiba",
    uf: "PR",
    estimatedValue: 134000,
    riskScore: 75,
    risk: "alto",
    confidence: 86,
    validationStatus: "rejeitado",
    responsible: "Davi Fadel",
    createdAt: daysAgo(12),
    summary: "Análise rejeitada pelo especialista por inconsistência na base de dados.",
    parties: [
      { role: "Reclamante", name: "Eduardo Pinto" },
      { role: "Reclamada", name: "Kapazi Industrial Ltda" },
      { role: "Vara/Tribunal", name: "89ª VT Curitiba — TRT9" },
    ],
    claims: [
      { claim: "Horas extras", estimatedValue: 54000, category: "Jornada", risk: "alto", confidence: 88 },
      { claim: "Verbas rescisórias", estimatedValue: 48000, category: "Rescisórias", risk: "alto", confidence: 84 },
      { claim: "Multa art. 467", estimatedValue: 32000, category: "Multas", risk: "medio", confidence: 80 },
    ],
    recommendations: ["Refazer análise com nova base"],
    sources: ["Processo mockado"],
    riskJustification: ["Dados de jornada inconsistentes"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-g1h3i5j7",
    estimatedCost: 0.47,
    rejectionReason: "Base de dados desatualizada — refazer com documentação atual.",
  },
  {
    id: "leg-8",
    processNumber: "0001199-66.2026.5.10.0021",
    companyId: "co-4",
    processType: "Cível",
    claimant: "Cliente Alpha LTDA",
    defendant: "Consultoria Tributária Alpha",
    lawyers: "Alpha Defesa",
    court: "21ª Vara Cível Brasília",
    uf: "DF",
    estimatedValue: 76000,
    riskScore: 41,
    risk: "medio",
    confidence: 81,
    validationStatus: "pendente",
    responsible: "Davi Fadel",
    createdAt: daysAgo(5),
    summary: "Ação de cobrança por serviços prestados. Documentação contratual completa.",
    parties: [
      { role: "Autor", name: "Cliente Alpha LTDA" },
      { role: "Réu", name: "Consultoria Tributária Alpha" },
      { role: "Vara/Tribunal", name: "21ª Vara Cível Brasília — TJDFT" },
    ],
    claims: [
      { claim: "Cobrança contratual", estimatedValue: 76000, category: "Contratual", risk: "medio", confidence: 81 },
    ],
    recommendations: ["Avaliar acordo", "Apresentar contraprova de entrega"],
    sources: ["Contrato mockado", "E-mails internos"],
    riskJustification: ["Contrato bem definido", "Comprovantes parciais de entrega"],
    engineVersion: "legal-engine-v1.0.0",
    promptHash: "legal-risk-2026-06-h9k2l4m6",
    estimatedCost: 0.39,
  },
];

const taxSummary =
  "A análise fiscal identificou inconsistências em registros de EFD ICMS/IPI e potenciais créditos tributários não aproveitados. O impacto financeiro estimado é relevante e recomenda validação técnica antes de qualquer ação de recuperação ou retificação.";

export const initialTaxAnalyses: TaxAnalysis[] = [
  {
    id: "tax-1",
    companyId: "co-1",
    fileType: "EFD ICMS/IPI",
    competence: "05/2026",
    inconsistenciesValue: 190200,
    opportunitiesValue: 330000,
    fiscalScore: 78,
    risk: "alto",
    confidence: 87,
    validationStatus: "pendente",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(1),
    summary: taxSummary,
    inconsistencies: [
      { type: "CFOP", registry: "C170", description: "Divergência de CFOP em operações interestaduais", value: 38500, severity: "medio", confidence: 86 },
      { type: "ICMS", registry: "E110", description: "Crédito de ICMS não aproveitado", value: 92000, severity: "alto", confidence: 91 },
      { type: "CST", registry: "C170", description: "Inconsistência em CST de saída", value: 18400, severity: "medio", confidence: 80 },
      { type: "Base de cálculo", registry: "E111", description: "Base de cálculo divergente", value: 41300, severity: "alto", confidence: 84 },
    ],
    opportunities: [
      { title: "Crédito ICMS potencial", value: 92000, description: "Créditos sobre insumos identificados como recuperáveis." },
      { title: "Revisão PIS/COFINS", value: 54000, description: "Reclassificação de itens não cumulativos." },
      { title: "Recuperação administrativa estimada", value: 184000, description: "Recuperação via PER/DCOMP mockada." },
      { title: "Impacto Reforma Tributária", value: 0, description: "Monitoramento recomendado para CBS/IBS." },
    ],
    recommendations: [
      "Validar amostra de documentos fiscais",
      "Revisar regras de CFOP e CST",
      "Analisar possibilidade de recuperação",
      "Submeter oportunidade ao especialista tributário",
      "Gerar relatório executivo para CFO",
    ],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-x1y2z3a4",
    estimatedCost: 0.58,
    financialImpact: 330000,
  },
  {
    id: "tax-2",
    companyId: "co-2",
    fileType: "EFD Contribuições",
    competence: "04/2026",
    inconsistenciesValue: 88000,
    opportunitiesValue: 142000,
    fiscalScore: 62,
    risk: "medio",
    confidence: 81,
    validationStatus: "pendente",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(2),
    summary: taxSummary,
    inconsistencies: [
      { type: "PIS", registry: "M210", description: "Apuração divergente de PIS não cumulativo", value: 42000, severity: "medio", confidence: 82 },
      { type: "COFINS", registry: "M610", description: "Crédito COFINS subaproveitado", value: 46000, severity: "alto", confidence: 85 },
    ],
    opportunities: [
      { title: "Revisão PIS/COFINS", value: 92000, description: "Reclassificação de insumos." },
      { title: "Recuperação administrativa", value: 50000, description: "Pedido de restituição mockado." },
    ],
    recommendations: ["Validar com tributarista", "Gerar relatório CFO"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-b5c6d7e8",
    estimatedCost: 0.41,
    financialImpact: 142000,
  },
  {
    id: "tax-3",
    companyId: "co-3",
    fileType: "XML NF-e",
    competence: "05/2026",
    inconsistenciesValue: 24500,
    opportunitiesValue: 0,
    fiscalScore: 34,
    risk: "baixo",
    confidence: 88,
    validationStatus: "aprovado",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(8),
    summary: "Análise de XML NF-e com baixa exposição. Pequenos ajustes em CFOP.",
    inconsistencies: [
      { type: "CFOP", registry: "NF-e", description: "CFOP 5102 incorretamente classificado", value: 24500, severity: "baixo", confidence: 88 },
    ],
    opportunities: [],
    recommendations: ["Ajuste pontual no ERP"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-f9g8h7i6",
    estimatedCost: 0.22,
    financialImpact: 24500,
  },
  {
    id: "tax-4",
    companyId: "co-1",
    fileType: "SPED ECF",
    competence: "2025",
    inconsistenciesValue: 124000,
    opportunitiesValue: 210000,
    fiscalScore: 71,
    risk: "alto",
    confidence: 79,
    validationStatus: "pendente",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(3),
    summary: taxSummary,
    inconsistencies: [
      { type: "IRPJ", registry: "M300", description: "Adição não realizada de despesa indedutível", value: 68000, severity: "alto", confidence: 82 },
      { type: "CSLL", registry: "M350", description: "Compensação de prejuízo incorreta", value: 56000, severity: "alto", confidence: 76 },
    ],
    opportunities: [
      { title: "Revisão de lucro real", value: 210000, description: "Recomposição de base com benefícios fiscais." },
    ],
    recommendations: ["Revisão da apuração", "Validar com auditoria"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-j2k3l4m5",
    estimatedCost: 0.62,
    financialImpact: 210000,
  },
  {
    id: "tax-5",
    companyId: "co-2",
    fileType: "EFD ICMS/IPI",
    competence: "03/2026",
    inconsistenciesValue: 64000,
    opportunitiesValue: 88000,
    fiscalScore: 55,
    risk: "medio",
    confidence: 74,
    validationStatus: "corrigido",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(11),
    summary: "Diagnóstico corrigido pelo especialista tributário após revisão.",
    inconsistencies: [
      { type: "ICMS-ST", registry: "C190", description: "Recolhimento divergente de ST", value: 64000, severity: "medio", confidence: 74 },
    ],
    opportunities: [
      { title: "Recuperação ICMS-ST", value: 88000, description: "Pedido de ressarcimento." },
    ],
    recommendations: ["Iniciar processo administrativo"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-n7o8p9q0",
    estimatedCost: 0.39,
    financialImpact: 88000,
  },
  {
    id: "tax-6",
    companyId: "co-4",
    fileType: "SPED ECD",
    competence: "2025",
    inconsistenciesValue: 14000,
    opportunitiesValue: 32000,
    fiscalScore: 28,
    risk: "baixo",
    confidence: 90,
    validationStatus: "aprovado",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(15),
    summary: "Escrituração contábil consistente. Pequenas oportunidades identificadas.",
    inconsistencies: [
      { type: "Conta", registry: "I150", description: "Reclassificação de conta de despesa", value: 14000, severity: "baixo", confidence: 90 },
    ],
    opportunities: [
      { title: "Ajuste contábil", value: 32000, description: "Reclassificação para benefício fiscal." },
    ],
    recommendations: ["Implementar reclassificação"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-r1s2t3u4",
    estimatedCost: 0.28,
    financialImpact: 32000,
  },
  {
    id: "tax-7",
    companyId: "co-3",
    fileType: "EFD Contribuições",
    competence: "05/2026",
    inconsistenciesValue: 158000,
    opportunitiesValue: 264000,
    fiscalScore: 84,
    risk: "critico",
    confidence: 85,
    validationStatus: "pendente",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(2),
    summary: taxSummary,
    inconsistencies: [
      { type: "PIS/COFINS", registry: "M205", description: "Subaproveitamento crítico de créditos", value: 158000, severity: "critico", confidence: 85 },
    ],
    opportunities: [
      { title: "Recuperação PIS/COFINS", value: 264000, description: "Janela de 5 anos." },
    ],
    recommendations: ["Priorizar revisão", "Avaliar PER/DCOMP"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-v5w6x7y8",
    estimatedCost: 0.71,
    financialImpact: 264000,
  },
  {
    id: "tax-8",
    companyId: "co-1",
    fileType: "XML NF-e",
    competence: "06/2026",
    inconsistenciesValue: 42000,
    opportunitiesValue: 58000,
    fiscalScore: 46,
    risk: "medio",
    confidence: 72,
    validationStatus: "pendente",
    responsible: "Nathan Endrigo",
    createdAt: daysAgo(1),
    summary: "Conjunto de XMLs com divergências de CST e oportunidades de crédito.",
    inconsistencies: [
      { type: "CST", registry: "NF-e", description: "CST PIS/COFINS divergente", value: 42000, severity: "medio", confidence: 72 },
    ],
    opportunities: [
      { title: "Crédito sobre insumos", value: 58000, description: "Identificação de itens elegíveis." },
    ],
    recommendations: ["Revisar parametrização do ERP"],
    engineVersion: "tax-engine-v1.0.0",
    promptHash: "tax-diag-2026-06-z9a0b1c2",
    estimatedCost: 0.35,
    financialImpact: 58000,
  },
];

export const initialDocuments: DocumentItem[] = [
  { id: "doc-1", name: "Processo_0001234.pdf", type: "juridico", companyId: "co-1", uploadedBy: "Renata Almeida", uploadedAt: daysAgo(1), status: "concluido", engine: "legal", analysisId: "leg-1" },
  { id: "doc-2", name: "EFD_ICMS_052026.txt", type: "tributario", companyId: "co-1", uploadedBy: "Nathan Endrigo", uploadedAt: daysAgo(1), status: "concluido", engine: "tax", analysisId: "tax-1" },
  { id: "doc-3", name: "Processo_0002231.pdf", type: "juridico", companyId: "co-2", uploadedBy: "Renata Almeida", uploadedAt: daysAgo(2), status: "concluido", engine: "legal", analysisId: "leg-2" },
  { id: "doc-4", name: "EFD_Contrib_042026.txt", type: "tributario", companyId: "co-2", uploadedBy: "Nathan Endrigo", uploadedAt: daysAgo(2), status: "concluido", engine: "tax", analysisId: "tax-2" },
  { id: "doc-5", name: "Contrato_servicos.pdf", type: "juridico", companyId: "co-4", uploadedBy: "Davi Fadel", uploadedAt: daysAgo(5), status: "concluido", engine: "legal", analysisId: "leg-8" },
  { id: "doc-6", name: "NFe_lote_062026.zip", type: "tributario", companyId: "co-1", uploadedBy: "Nathan Endrigo", uploadedAt: daysAgo(1), status: "processando", engine: "tax" },
];

export const decisionRecommendations: DecisionRecommendation[] = [
  { id: "dec-1", title: "Revisar processo trabalhista de alto risco", origin: "Legal", originId: "leg-1", financialImpact: 113000, urgency: "alto", priorityScore: 92, suggestedOwner: "Renata Almeida", status: "pendente", recommendedAction: "Validar documentos e avaliar acordo." },
  { id: "dec-2", title: "Validar oportunidade tributária de ICMS", origin: "Tax", originId: "tax-1", financialImpact: 184000, urgency: "medio", priorityScore: 86, suggestedOwner: "Nathan Endrigo", status: "pendente", recommendedAction: "Abrir análise técnica." },
  { id: "dec-3", title: "Consolidar exposição jurídico-tributária da unidade Sul", origin: "Cross", financialImpact: 420000, urgency: "alto", priorityScore: 95, suggestedOwner: "Mariana Costa (CFO)", status: "pendente", recommendedAction: "Reunião CFO + jurídico + tributário." },
  { id: "dec-4", title: "Priorizar acordo em processo crítico TRT12", origin: "Legal", originId: "leg-3", financialImpact: 198000, urgency: "critico", priorityScore: 97, suggestedOwner: "Davi Fadel", status: "pendente", recommendedAction: "Buscar acordo até 60% do valor." },
  { id: "dec-5", title: "Recuperação PIS/COFINS crítica", origin: "Tax", originId: "tax-7", financialImpact: 264000, urgency: "alto", priorityScore: 90, suggestedOwner: "Nathan Endrigo", status: "pendente", recommendedAction: "Avaliar janela prescricional." },
  { id: "dec-6", title: "Refazer análise jurídica rejeitada", origin: "Legal", originId: "leg-7", financialImpact: 134000, urgency: "medio", priorityScore: 70, suggestedOwner: "Davi Fadel", status: "em_revisao", recommendedAction: "Atualizar base de dados e reprocessar." },
  { id: "dec-7", title: "Revisar apuração de IRPJ/CSLL 2025", origin: "Tax", originId: "tax-4", financialImpact: 210000, urgency: "alto", priorityScore: 88, suggestedOwner: "Nathan Endrigo", status: "pendente", recommendedAction: "Revalidar adições e compensações." },
  { id: "dec-8", title: "Acompanhar audiência trabalhista PR", origin: "Legal", originId: "leg-4", financialImpact: 42000, urgency: "baixo", priorityScore: 45, suggestedOwner: "Renata Almeida", status: "em_revisao", recommendedAction: "Confirmar pauta e defesa." },
  { id: "dec-9", title: "Cross-checking jurídico+tributário Kapazi", origin: "Cross", financialImpact: 380000, urgency: "alto", priorityScore: 91, suggestedOwner: "Delmer Zoschke (CEO)", status: "pendente", recommendedAction: "Briefing executivo consolidado." },
  { id: "dec-10", title: "Revisão de PIS/COFINS unidade SP", origin: "Tax", originId: "tax-2", financialImpact: 142000, urgency: "medio", priorityScore: 78, suggestedOwner: "Nathan Endrigo", status: "pendente", recommendedAction: "Submeter à validação especialista." },
];

const actions = [
  "user.login", "document.upload", "document.processed",
  "legal.analysis.generated", "tax.diagnosis.generated",
  "analysis.approved", "analysis.corrected", "analysis.rejected",
  "recommendation.created", "report.generated", "settings.updated",
];

export const initialAuditLogs: AuditLog[] = Array.from({ length: 32 }).map((_, i) => {
  const u = users[i % users.length];
  const action = actions[i % actions.length];
  const isEngine = action.includes("legal") || action.includes("tax");
  return {
    id: `log-${i + 1}`,
    timestamp: new Date(now - i * 3600000 * 2).toISOString(),
    userEmail: u.email,
    userRole: u.role,
    action,
    resource: action.split(".")[0],
    companyId: companies[i % companies.length].id,
    engine: isEngine ? (action.includes("legal") ? "legal" : "tax") : undefined,
    engineVersion: isEngine ? (action.includes("legal") ? "legal-engine-v1.0.0" : "tax-engine-v1.0.0") : undefined,
    promptHash: isEngine ? `hash-${i}-a${i}b${i}c` : undefined,
    ip: `200.${(i * 7) % 255}.${(i * 13) % 255}.${(i * 3) % 255}`,
    result: i % 11 === 0 ? "error" : "success",
  };
});

// Knowledge Graph
export const graphNodes: GraphNode[] = [
  { id: "n-emp1", label: "Kapazi Industrial", type: "Empresa", description: "Indústria — cliente fundador.", x: 400, y: 60 },
  { id: "n-emp2", label: "Varejo Nacional", type: "Empresa", description: "Varejo nacional.", x: 100, y: 60 },
  { id: "n-emp3", label: "Indústria Sul", type: "Empresa", description: "Unidade Sul.", x: 700, y: 60 },
  { id: "n-proc1", label: "Processo 0001234", type: "Processo", description: "Processo trabalhista em Curitiba.", x: 380, y: 180 },
  { id: "n-proc2", label: "Processo 0008452", type: "Processo", description: "Processo crítico TRT12.", x: 680, y: 180 },
  { id: "n-ped1", label: "Horas Extras", type: "Pedido", description: "Pedido recorrente de jornada.", x: 280, y: 290 },
  { id: "n-ped2", label: "Insalubridade", type: "Pedido", description: "Adicional de insalubridade.", x: 420, y: 290 },
  { id: "n-ped3", label: "Verbas Rescisórias", type: "Pedido", description: "Rescisórias em massa.", x: 680, y: 290 },
  { id: "n-tese1", label: "Tese: Jornada", type: "Tese", description: "Tese sobre controle de jornada.", x: 200, y: 400 },
  { id: "n-risc1", label: "Risco Alto Trabalhista", type: "Risco", description: "Exposição relevante.", x: 380, y: 400 },
  { id: "n-risc2", label: "Risco Crítico TRT12", type: "Risco", description: "Risco crítico identificado.", x: 680, y: 400 },
  { id: "n-rec1", label: "Recomendação: Acordo", type: "Recomendação", description: "Avaliar acordo até R$ 42k.", x: 380, y: 510 },
  { id: "n-rec2", label: "Recomendação: Defesa Reforçada", type: "Recomendação", description: "Reforçar defesa técnica.", x: 680, y: 510 },
  { id: "n-val1", label: "Validação Jurídica", type: "Validação", description: "Aguardando especialista jurídico.", x: 380, y: 610 },
  { id: "n-esp1", label: "Davi Fadel", type: "Especialista", description: "Inteligência Jurídica.", x: 200, y: 610 },
  { id: "n-sped", label: "SPED EFD", type: "Tributo", description: "Escrituração fiscal Kapazi.", x: 540, y: 180 },
  { id: "n-trib1", label: "ICMS", type: "Tributo", description: "Tributo ICMS.", x: 540, y: 290 },
  { id: "n-cred1", label: "Crédito ICMS", type: "Crédito", description: "Crédito de R$ 92.000 identificado.", x: 540, y: 400 },
  { id: "n-op1", label: "Oportunidade Tributária", type: "Oportunidade", description: "Recuperação estimada R$ 184k.", x: 540, y: 510 },
  { id: "n-val2", label: "Validação Tributária", type: "Validação", description: "Aguardando tributarista.", x: 540, y: 610 },
];

export const graphEdges: GraphEdge[] = [
  { from: "n-emp1", to: "n-proc1" }, { from: "n-emp1", to: "n-sped" }, { from: "n-emp3", to: "n-proc2" },
  { from: "n-proc1", to: "n-ped1" }, { from: "n-proc1", to: "n-ped2" }, { from: "n-proc2", to: "n-ped3" },
  { from: "n-ped1", to: "n-tese1" }, { from: "n-ped1", to: "n-risc1" }, { from: "n-ped2", to: "n-risc1" },
  { from: "n-ped3", to: "n-risc2" }, { from: "n-risc1", to: "n-rec1" }, { from: "n-risc2", to: "n-rec2" },
  { from: "n-rec1", to: "n-val1" }, { from: "n-rec2", to: "n-val1" }, { from: "n-val1", to: "n-esp1" },
  { from: "n-sped", to: "n-trib1" }, { from: "n-trib1", to: "n-cred1" }, { from: "n-cred1", to: "n-op1" },
  { from: "n-op1", to: "n-val2" }, { from: "n-emp2", to: "n-sped" },
  { from: "n-emp1", to: "n-proc2", label: "exposição cruzada" },
  { from: "n-tese1", to: "n-rec1" }, { from: "n-emp3", to: "n-sped" },
  { from: "n-proc1", to: "n-risc1" }, { from: "n-proc2", to: "n-risc2" },
  { from: "n-ped3", to: "n-rec2" }, { from: "n-op1", to: "n-rec1" },
  { from: "n-cred1", to: "n-rec1" }, { from: "n-val2", to: "n-esp1" },
  { from: "n-risc1", to: "n-val1" }, { from: "n-risc2", to: "n-val1" },
];
