import type { RadarUpdate, JurimetryClaim, JurimetryPending, JurimetrySuggestion, AuditLog } from "./types";

const today = new Date();
const d = (offset: number) => new Date(today.getTime() - offset * 86400000).toISOString();
const uid = (p: string, i: number) => `${p}-${i}`;

// 12 radar updates: 6 trabalhista, 4 tributário, 2 reforma
export const initialRadarUpdates: RadarUpdate[] = [
  {
    id: uid("rad", 1),
    title: "Nova tendência em pedidos de horas extras em decisões recentes",
    area: "Trabalhista",
    source: "Radar Trabalhista Simulado",
    date: d(0),
    relevance: "alto",
    impactedCount: 37,
    impactedKind: "processos",
    summary: "A atualização pode impactar processos com pedidos de horas extras e baixa documentação de controle de jornada.",
    whyMatters: "37 processos da carteira possuem o pedido principal de horas extras combinado com lacunas documentais de controle de jornada — recomenda-se reavaliação de risco.",
    suggestedAction: "Revisar processos com pedido de horas extras e risco acima de 70.",
    companyId: "co-1",
    status: "novo",
    impacts: [
      { kind: "processo", ref: "0001234-56.2026.5.09.0001", detail: "Horas extras", risk: "alto" },
      { kind: "processo", ref: "0008452-88.2025.5.12.0044", detail: "Intervalo intrajornada", risk: "medio" },
      { kind: "processo", ref: "0007781-22.2026.5.03.0101", detail: "Horas extras + reflexos", risk: "alto" },
    ],
    suggestions: [
      { id: "rsg-1a", title: "Revisar classificação de risco", priority: "alto", owner: "Renata Almeida", deadline: "5 dias úteis", reason: "Padrão recorrente em 37 processos." },
      { id: "rsg-1b", title: "Solicitar documentos complementares", priority: "medio", owner: "Equipe Jurídica", deadline: "10 dias úteis", reason: "Falta de cartões de ponto em parte dos casos." },
    ],
  },
  {
    id: uid("rad", 2),
    title: "Discussão sobre adicional de insalubridade ganha relevância em carteiras industriais",
    area: "Trabalhista",
    source: "Jurisprudência Simulada",
    date: d(1),
    relevance: "medio",
    impactedCount: 12,
    impactedKind: "processos",
    summary: "A CognIA identificou processos com pedido de adicional de insalubridade e documentação técnica incompleta.",
    whyMatters: "Em carteiras com perfil industrial, decisões recentes têm sido sensíveis à existência de laudo técnico atualizado.",
    suggestedAction: "Solicitar validação do especialista jurídico.",
    companyId: "co-2",
    status: "novo",
    impacts: [
      { kind: "processo", ref: "0004412-77.2024.5.02.0033", detail: "Adicional de insalubridade", risk: "medio" },
      { kind: "processo", ref: "0009931-11.2025.5.04.0220", detail: "Insalubridade + reflexos", risk: "alto" },
    ],
    suggestions: [
      { id: "rsg-2a", title: "Atualizar tese defensiva", priority: "medio", owner: "Renata Almeida", deadline: "7 dias úteis", reason: "Tendência jurisprudencial em curso." },
    ],
  },
  {
    id: uid("rad", 3),
    title: "Possível oportunidade de crédito de ICMS em operações interestaduais",
    area: "Tributário",
    source: "Radar Tributário Simulado",
    date: d(1),
    relevance: "alto",
    impactedCount: 8,
    impactedKind: "documentos",
    summary: "A análise pode indicar oportunidade de revisão em operações com CFOP específico.",
    whyMatters: "8 arquivos fiscais recentes registram CFOPs com perfil de crédito ainda não aproveitado.",
    suggestedAction: "Executar diagnóstico tributário nos documentos relacionados.",
    companyId: "co-1",
    status: "novo",
    impacts: [
      { kind: "documento", ref: "EFD ICMS/IPI 05/2026", detail: "CFOP 6.102", risk: "medio" },
      { kind: "documento", ref: "EFD ICMS/IPI 04/2026", detail: "CFOP 6.108", risk: "medio" },
    ],
    suggestions: [
      { id: "rsg-3a", title: "Gerar relatório executivo", priority: "alto", owner: "Nathan Endrigo", deadline: "3 dias úteis", reason: "Oportunidade financeira relevante." },
    ],
  },
  {
    id: uid("rad", 4),
    title: "Reforma Tributária: nova regra simulada pode alterar carga de determinados produtos",
    area: "Reforma Tributária",
    source: "Monitor Regulatório Simulado",
    date: d(2),
    relevance: "critico",
    impactedCount: 2,
    impactedKind: "empresas",
    summary: "A atualização pode exigir simulação de impacto em clientes com operação industrial e varejista.",
    whyMatters: "Mudança simulada de alíquota afeta diretamente cadeias de varejo e indústria; recomenda-se avaliação prioritária.",
    suggestedAction: "Gerar relatório executivo para CFO.",
    companyId: "co-3",
    status: "novo",
    impacts: [
      { kind: "diagnostico", ref: "Diagnóstico CFO 06/2026", detail: "Simulação de impacto pendente" },
    ],
    suggestions: [
      { id: "rsg-4a", title: "Gerar relatório executivo", priority: "critico", owner: "Mariana Costa", deadline: "2 dias úteis", reason: "Tema sensível para o board." },
      { id: "rsg-4b", title: "Enviar para validação humana", priority: "alto", owner: "Comitê Tributário", deadline: "5 dias úteis", reason: "Necessária validação técnica." },
    ],
  },
  {
    id: uid("rad", 5),
    title: "Pedidos de acúmulo de função em ascensão em decisões regionais",
    area: "Trabalhista",
    source: "Radar Trabalhista Simulado",
    date: d(3),
    relevance: "medio",
    impactedCount: 18,
    impactedKind: "processos",
    summary: "Aumenta a recorrência de condenações por acúmulo de função quando a descrição de cargo é genérica.",
    whyMatters: "18 processos da carteira apresentam descrição de cargo incompleta no anexo de admissão.",
    suggestedAction: "Revisar classificação de pedidos correlatos.",
    companyId: "co-2",
    status: "analisado",
    impacts: [],
    suggestions: [
      { id: "rsg-5a", title: "Revisar classificação de risco", priority: "medio", owner: "Renata Almeida", deadline: "10 dias úteis", reason: "Tendência regional." },
    ],
  },
  {
    id: uid("rad", 6),
    title: "Equiparação salarial — nova tese ganha tração em TRTs do Sudeste",
    area: "Trabalhista",
    source: "Jurisprudência Simulada",
    date: d(4),
    relevance: "alto",
    impactedCount: 9,
    impactedKind: "processos",
    summary: "Decisões recentes reforçam exigência de paradigma com mesma função, mesmo local e mesmo empregador.",
    whyMatters: "9 processos da carteira têm pedido de equiparação salarial com paradigmas insuficientemente comprovados.",
    suggestedAction: "Solicitar validação do especialista jurídico.",
    companyId: "co-4",
    status: "novo",
    impacts: [],
    suggestions: [
      { id: "rsg-6a", title: "Atualizar tese defensiva", priority: "alto", owner: "Renata Almeida", deadline: "7 dias úteis", reason: "Tese consolidada em tribunais." },
    ],
  },
  {
    id: uid("rad", 7),
    title: "Atualização sobre intervalo intrajornada em escalas 12x36",
    area: "Trabalhista",
    source: "Radar Trabalhista Simulado",
    date: d(5),
    relevance: "medio",
    impactedCount: 14,
    impactedKind: "processos",
    summary: "Mudança de entendimento pode impactar empresas com escala 12x36 sem registro adequado.",
    whyMatters: "14 processos da carteira contemplam jornada 12x36 com lacunas de registro.",
    suggestedAction: "Revisar processos com pedido de intervalo intrajornada.",
    companyId: "co-1",
    status: "em_revisao",
    impacts: [],
    suggestions: [
      { id: "rsg-7a", title: "Solicitar documentos complementares", priority: "medio", owner: "Equipe Jurídica", deadline: "7 dias úteis", reason: "Registros parciais." },
    ],
  },
  {
    id: uid("rad", 8),
    title: "Dano moral coletivo — nova orientação simulada",
    area: "Trabalhista",
    source: "Jurisprudência Simulada",
    date: d(6),
    relevance: "alto",
    impactedCount: 4,
    impactedKind: "processos",
    summary: "Reforço de tese pode aumentar exposição em ações coletivas trabalhistas.",
    whyMatters: "4 processos da carteira tratam de tema correlato com risco potencial relevante.",
    suggestedAction: "Enviar para validação humana.",
    companyId: "co-5",
    status: "novo",
    impacts: [],
    suggestions: [
      { id: "rsg-8a", title: "Enviar para validação humana", priority: "alto", owner: "Comitê Jurídico", deadline: "5 dias úteis", reason: "Alto impacto reputacional." },
    ],
  },
  {
    id: uid("rad", 9),
    title: "PIS/COFINS — nova interpretação simulada de exclusão de base",
    area: "Tributário",
    source: "Radar Tributário Simulado",
    date: d(2),
    relevance: "alto",
    impactedCount: 11,
    impactedKind: "documentos",
    summary: "Interpretação pode liberar oportunidade de revisão das bases de cálculo nos últimos 5 anos.",
    whyMatters: "11 documentos analisados podem ser elegíveis à revisão.",
    suggestedAction: "Executar diagnóstico tributário consolidado.",
    companyId: "co-1",
    status: "novo",
    impacts: [],
    suggestions: [
      { id: "rsg-9a", title: "Gerar relatório executivo", priority: "alto", owner: "Nathan Endrigo", deadline: "5 dias úteis", reason: "Oportunidade financeira recorrente." },
    ],
  },
  {
    id: uid("rad", 10),
    title: "Compliance — atualização simulada do programa de integridade",
    area: "Compliance",
    source: "Monitor Regulatório Simulado",
    date: d(3),
    relevance: "medio",
    impactedCount: 3,
    impactedKind: "empresas",
    summary: "Reforço de exigências de controles internos para fornecedores e parceiros.",
    whyMatters: "3 empresas do portfólio têm programa de integridade desatualizado em mais de 18 meses.",
    suggestedAction: "Recomenda-se atualizar políticas de due diligence.",
    companyId: "co-3",
    status: "analisado",
    impacts: [],
    suggestions: [
      { id: "rsg-10a", title: "Gerar relatório executivo", priority: "medio", owner: "Compliance", deadline: "15 dias úteis", reason: "Risco regulatório crescente." },
    ],
  },
  {
    id: uid("rad", 11),
    title: "Crédito presumido — possível ampliação em segmentos industriais",
    area: "Tributário",
    source: "Radar Tributário Simulado",
    date: d(4),
    relevance: "medio",
    impactedCount: 6,
    impactedKind: "documentos",
    summary: "Mudança pode beneficiar operações específicas com produto controlado.",
    whyMatters: "6 documentos fiscais podem ser elegíveis a revisão de créditos presumidos.",
    suggestedAction: "Sugere-se revisar amostra fiscal das últimas competências.",
    companyId: "co-4",
    status: "novo",
    impacts: [],
    suggestions: [
      { id: "rsg-11a", title: "Solicitar documentos complementares", priority: "medio", owner: "Nathan Endrigo", deadline: "10 dias úteis", reason: "Necessário levantamento adicional." },
    ],
  },
  {
    id: uid("rad", 12),
    title: "Reforma Tributária — nova nota técnica simulada sobre transição",
    area: "Reforma Tributária",
    source: "Monitor Regulatório Simulado",
    date: d(5),
    relevance: "alto",
    impactedCount: 5,
    impactedKind: "empresas",
    summary: "Cronograma de transição pode exigir reorganização de operações industriais e logísticas.",
    whyMatters: "5 empresas da carteira podem precisar revisar contratos e custos.",
    suggestedAction: "Gerar relatório executivo para CFO e jurídico.",
    companyId: "co-2",
    status: "novo",
    impacts: [],
    suggestions: [
      { id: "rsg-12a", title: "Gerar relatório executivo", priority: "alto", owner: "Mariana Costa", deadline: "7 dias úteis", reason: "Decisões estratégicas em curso." },
    ],
  },
];

// ===== Jurimetria =====
export const jurimetryAggregates = {
  processes: 22840,
  claims: 329358,
  successPct: 60.6,
  agreementPct: 16.6,
  convictionPct: 17.0,
  avgAgreement: 32700,
  avgConviction: 30400,
  qualityPct: 93.2,
  pendingFields: 1284,
};

export const jurimetryClaims: JurimetryClaim[] = [
  ["13º salário", 12480, 64, 18, 12, 4, 2, 18400, 22300, 42, 88, "aprovado"],
  ["Abono aposentadoria", 1890, 71, 12, 9, 6, 2, 15200, 17800, 38, 81, "pendente"],
  ["Abono férias", 3120, 69, 14, 11, 4, 2, 12400, 14900, 36, 84, "aprovado"],
  ["Abono PIS", 980, 78, 9, 7, 4, 2, 9800, 11000, 28, 79, "pendente"],
  ["Abono salarial", 1420, 73, 11, 8, 5, 3, 11200, 13500, 34, 80, "pendente"],
  ["Acidente de trabalho", 2240, 41, 22, 27, 7, 3, 48000, 62000, 71, 86, "aprovado"],
  ["Acidente de trabalho COVID", 480, 38, 24, 29, 6, 3, 51000, 67000, 78, 74, "pendente"],
  ["Acúmulo de função", 3380, 49, 21, 22, 5, 3, 27000, 31000, 62, 82, "aprovado"],
  ["Acúmulo de função e reflexos", 1820, 47, 22, 24, 4, 3, 29000, 33000, 64, 78, "pendente"],
  ["Adicional de insalubridade", 4980, 44, 19, 28, 6, 3, 33000, 41000, 68, 85, "aprovado"],
  ["Adicional de periculosidade", 2630, 42, 18, 30, 7, 3, 35000, 42000, 70, 86, "aprovado"],
  ["Horas extras", 18920, 55, 21, 17, 5, 2, 28000, 36000, 73, 91, "pendente"],
  ["Intervalo intrajornada", 9430, 58, 19, 16, 5, 2, 21000, 25000, 61, 87, "aprovado"],
  ["Verbas rescisórias", 14210, 67, 17, 11, 4, 1, 24000, 28000, 49, 89, "aprovado"],
  ["Dano moral", 6210, 39, 23, 30, 6, 2, 38000, 49000, 76, 80, "pendente"],
  ["Equiparação salarial", 2280, 36, 24, 32, 6, 2, 41000, 52000, 79, 77, "pendente"],
].map(([claim, count, s, a, c, cl, e, va, vc, r, conf, val]) => ({
  claim: claim as string,
  count: count as number,
  successPct: s as number,
  agreementPct: a as number,
  convictionPct: c as number,
  closedPct: cl as number,
  extinctPct: e as number,
  avgAgreement: va as number,
  avgConviction: vc as number,
  avgRisk: r as number,
  confidence: conf as number,
  validation: val as JurimetryClaim["validation"],
}));

export const jurimetryPendings: JurimetryPending[] = Array.from({ length: 30 }, (_, i) => {
  const fields = ["Pedido", "Resultado", "Valor", "Tribunal", "Advogado", "Tese"];
  const suggested = ["Horas extras", "Acordo", "R$ 42.000", "TRT 9ª", "Escritório Mock", "Documentação parcial"];
  const responsibles = ["Renata Almeida", "Davi Fadel", "Nathan Endrigo"];
  const idx = i % 6;
  return {
    id: `jp-${i + 1}`,
    processNumber: `000${1000 + i}-${10 + (i % 89)}.2026.5.0${(i % 9) + 1}.000${(i % 9) + 1}`,
    field: fields[idx],
    suggested: suggested[idx],
    confidence: 60 + Math.floor(Math.random() * 35),
    status: (i % 5 === 0 ? "aprovado" : i % 7 === 0 ? "corrigido" : "pendente") as JurimetryPending["status"],
    responsible: responsibles[i % 3],
  };
});

export const jurimetrySuggestions: JurimetrySuggestion[] = [
  { id: "js-1", title: "Revisar processos de horas extras com baixa documentação", reason: "Carteira concentra exposição em pedido com risco médio 73.", impactedProcesses: 37, financialImpact: 1_200_000, priority: "alto", confidence: 88, owner: "Renata Almeida", action: "Enviar para validação jurídica" },
  { id: "js-2", title: "Classificar pedidos pendentes de acúmulo de função", reason: "Há 18 processos com classificação automática pendente.", impactedProcesses: 18, financialImpact: 480_000, priority: "medio", confidence: 84, owner: "Davi Fadel", action: "Aprovar categorização sugerida pela IA" },
  { id: "js-3", title: "Atualizar risco de adicional de insalubridade", reason: "Tendência regional eleva risco para perfil industrial.", impactedProcesses: 12, financialImpact: 390_000, priority: "alto", confidence: 82, owner: "Renata Almeida", action: "Revisar com especialista" },
  { id: "js-4", title: "Completar campos ausentes de valor estimado", reason: "78 processos sem valor estimado validado.", impactedProcesses: 78, financialImpact: 0, priority: "medio", confidence: 76, owner: "Equipe Jurídica", action: "Aprovar valores sugeridos" },
  { id: "js-5", title: "Agrupar processos semelhantes para tese unificada", reason: "26 processos com pedido recorrente e mesma defesa.", impactedProcesses: 26, financialImpact: 720_000, priority: "medio", confidence: 80, owner: "Renata Almeida", action: "Criar lote para revisão" },
  { id: "js-6", title: "Reavaliar valores médios de acordo", reason: "Variação acima de 18% em relação à média histórica.", impactedProcesses: 9, financialImpact: 240_000, priority: "medio", confidence: 73, owner: "Davi Fadel", action: "Solicitar revisão do especialista" },
  { id: "js-7", title: "Gerar relatório executivo de jurimetria", reason: "Carteira sem relatório consolidado nos últimos 30 dias.", impactedProcesses: 22840, financialImpact: 0, priority: "baixo", confidence: 95, owner: "Mariana Costa", action: "Gerar PDF mockado" },
  { id: "js-8", title: "Enviar lote para validação humana", reason: "320 sugestões da IA aguardam revisão final.", impactedProcesses: 320, financialImpact: 0, priority: "alto", confidence: 90, owner: "Comitê Jurídico", action: "Encaminhar lote" },
  { id: "js-9", title: "Corrigir classificação de pedido de dano moral", reason: "12 processos classificados como genéricos.", impactedProcesses: 12, financialImpact: 310_000, priority: "medio", confidence: 78, owner: "Renata Almeida", action: "Aprovar reclassificação" },
  { id: "js-10", title: "Reavaliar tese defensiva de equiparação salarial", reason: "Tese atual com taxa de êxito abaixo do benchmark.", impactedProcesses: 14, financialImpact: 560_000, priority: "alto", confidence: 83, owner: "Renata Almeida", action: "Atualizar tese e validar" },
];

// History 2019-2026
export const jurimetryHistory = [
  { year: 2019, success: 56, agreement: 18, conviction: 19 },
  { year: 2020, success: 58, agreement: 17, conviction: 18 },
  { year: 2021, success: 59, agreement: 16, conviction: 18 },
  { year: 2022, success: 60, agreement: 17, conviction: 17 },
  { year: 2023, success: 61, agreement: 16, conviction: 17 },
  { year: 2024, success: 60, agreement: 17, conviction: 17 },
  { year: 2025, success: 61, agreement: 16, conviction: 16 },
  { year: 2026, success: 61, agreement: 17, conviction: 17 },
];

export const jurimetryByCity = [
  { city: "São Paulo · TRT 2", count: 5240, success: 62 },
  { city: "Campinas · TRT 15", count: 2810, success: 58 },
  { city: "Curitiba · TRT 9", count: 2240, success: 64 },
  { city: "Belo Horizonte · TRT 3", count: 2010, success: 59 },
  { city: "Porto Alegre · TRT 4", count: 1820, success: 61 },
  { city: "Rio de Janeiro · TRT 1", count: 1640, success: 57 },
  { city: "Salvador · TRT 5", count: 1180, success: 60 },
  { city: "Recife · TRT 6", count: 980, success: 63 },
];

export const initialRadarLogs: AuditLog[] = Array.from({ length: 20 }, (_, i) => ({
  id: `rlog-${i + 1}`,
  timestamp: d(i % 7),
  userEmail: ["renata@cognia.ai", "nathan@cognia.ai", "mariana@cognia.ai"][i % 3],
  userRole: (["Diretor Jurídico", "Diretor Tributário", "CFO"] as const)[i % 3],
  action: ["radar.update.viewed", "radar.impact.generated", "radar.action.created", "radar.action.sent_to_validation", "radar.recommendation.dismissed"][i % 5],
  resource: "radar",
  companyId: ["co-1", "co-2", "co-3"][i % 3],
  engine: "radar",
  engineVersion: "radar-engine-v0.9.0",
  promptHash: `radar-${i.toString(16).padStart(6, "0")}`,
  ip: "200.158.42.10",
  result: "success" as const,
}));

export const initialJurimetryLogs: AuditLog[] = Array.from({ length: 30 }, (_, i) => ({
  id: `jlog-${i + 1}`,
  timestamp: d(i % 14),
  userEmail: ["renata@cognia.ai", "davi@cognia.ai", "mariana@cognia.ai"][i % 3],
  userRole: (["Diretor Jurídico", "Administrador", "CFO"] as const)[i % 3],
  action: [
    "jurimetry.dashboard.viewed", "jurimetry.claim.filtered", "jurimetry.field.approved",
    "jurimetry.field.corrected", "jurimetry.field.rejected", "jurimetry.suggestion.created",
    "jurimetry.suggestion.sent_to_validation", "jurimetry.report.generated",
  ][i % 8],
  resource: "jurimetry",
  companyId: ["co-1", "co-2", "co-3", "co-4"][i % 4],
  engine: "legal",
  engineVersion: "legal-engine-v1.0.0",
  promptHash: `juri-${i.toString(16).padStart(6, "0")}`,
  ip: "200.158.42.10",
  result: "success" as const,
}));
