/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaxIndexRouteImport } from './routes/tax.index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as TaxIdRouteImport } from './routes/tax.$id'
import { Route as LegalIdRouteImport } from './routes/legal.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxIndexRoute = TaxIndexRouteImport.update({
  id: '/tax/',
  path: '/tax/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxIdRoute = TaxIdRouteImport.update({
  id: '/tax/$id',
  path: '/tax/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIdRoute = LegalIdRouteImport.update({
  id: '/legal/$id',
  path: '/legal/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/legal/$id': typeof LegalIdRoute
  '/tax/$id': typeof TaxIdRoute
  '/legal/': typeof LegalIndexRoute
  '/tax/': typeof TaxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/legal/$id': typeof LegalIdRoute
  '/tax/$id': typeof TaxIdRoute
  '/legal': typeof LegalIndexRoute
  '/tax': typeof TaxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/legal/$id': typeof LegalIdRoute
  '/tax/$id': typeof TaxIdRoute
  '/legal/': typeof LegalIndexRoute
  '/tax/': typeof TaxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/legal/$id'
    | '/tax/$id'
    | '/legal/'
    | '/tax/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/legal/$id'
    | '/tax/$id'
    | '/legal'
    | '/tax'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/legal/$id'
    | '/tax/$id'
    | '/legal/'
    | '/tax/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  LegalIdRoute: typeof LegalIdRoute
  TaxIdRoute: typeof TaxIdRoute
  LegalIndexRoute: typeof LegalIndexRoute
  TaxIndexRoute: typeof TaxIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/': {
      id: '/tax/'
      path: '/tax'
      fullPath: '/tax/'
      preLoaderRoute: typeof TaxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/$id': {
      id: '/tax/$id'
      path: '/tax/$id'
      fullPath: '/tax/$id'
      preLoaderRoute: typeof TaxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$id': {
      id: '/legal/$id'
      path: '/legal/$id'
      fullPath: '/legal/$id'
      preLoaderRoute: typeof LegalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  LegalIdRoute: LegalIdRoute,
  TaxIdRoute: TaxIdRoute,
  LegalIndexRoute: LegalIndexRoute,
  TaxIndexRoute: TaxIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
